#!/usr/bin/env bash
# Generate the release compose file from the development one.
#
# WHY GENERATE RATHER THAN COMMIT A SECOND FILE: the dev compose builds the `easydocs` service from
# source (`build: {context: ../..}`), which is right for development and for CI (both run
# `up --build` against the working tree). A release bundle has no source tree, so it must reference
# the published image instead. Maintaining that as a hand-written second file is how the two drift:
# someone adds a service or an env var to one and forgets the other, and nobody notices until a
# release is already out. Deriving it from the single source of truth makes drift impossible.
#
# The transform is deliberately narrow: replace the `easydocs` service's `build:` block with a pinned
# `image:`, and drop `env_file:` (the bundle ships .env next to the compose file, but `env_file` on a
# path that may not exist is a hard error, whereas compose reads ./.env for interpolation anyway).
# Everything else — services, ports, volumes, healthchecks, depends_on — is passed through verbatim.
#
# Usage: gen-release-compose.sh <image-ref> [source] [dest]
set -euo pipefail

IMAGE="${1:?usage: gen-release-compose.sh <image-ref> [source] [dest]}"
SRC="${2:-deploy/compose/docker-compose.yml}"
DEST="${3:-/dev/stdout}"

python3 - "$IMAGE" "$SRC" "$DEST" <<'PY'
import re, sys

image, src, dest = sys.argv[1], sys.argv[2], sys.argv[3]
lines = open(src).read().splitlines(keepends=True)

out, i = [], 0
replaced_build = False
while i < len(lines):
    line = lines[i]
    # The build block: `    build:` followed by its more-indented children.
    if re.match(r'^\s{4}build:\s*$', line):
        indent = len(line) - len(line.lstrip())
        out.append(' ' * indent + f'image: {image}\n')
        replaced_build = True
        i += 1
        while i < len(lines):
            nxt = lines[i]
            if nxt.strip() and (len(nxt) - len(nxt.lstrip())) <= indent:
                break
            i += 1
        continue
    # env_file is kept, but made optional. Dropping it entirely was wrong: compose reads ./.env for
    # ${VAR} interpolation, which only covers the handful of keys `environment:` names explicitly —
    # everything else a self-hoster is told to set in .env (RateLimit__*, and
    # ASPNETCORE_FORWARDEDHEADERS_ENABLED, which SECURITY.md tells them they need behind a proxy)
    # never reached the container. They would edit .env, restart, and nothing would happen. The
    # long-form `required: false` (Compose 2.24+) keeps the original reason for removing it — a bundle
    # unpacked without a .env must still start — without silently discarding the tunables.
    if re.match(r'^\s{4}env_file:', line):
        indent = len(line) - len(line.lstrip())
        pad = ' ' * indent
        out.append(f'{pad}env_file:\n{pad}  - path: .env\n{pad}    required: false\n')
        i += 1
        continue
    out.append(line)
    i += 1

if not replaced_build:
    sys.exit(f'gen-release-compose: no `build:` block found in {src} — the transform matched nothing, '
             'which means the dev compose changed shape. Fix this script rather than shipping an '
             'unpinned bundle.')

header = (
    '# GENERATED by .github/scripts/gen-release-compose.sh — do not edit by hand.\n'
    '# Derived from deploy/compose/docker-compose.yml with the source build replaced by a pinned\n'
    f'# published image ({image}).\n'
    '#\n'
    '# Quickstart:  cp .env.example .env  &&  edit the secrets  &&  docker compose up -d\n'
    '# Jwt__Secret must be at least 32 bytes or the app deliberately fails fast at boot.\n'
    '# Serve this behind TLS: the session cookie is Secure, so a browser silently discards it over\n'
    '# plain HTTP on a LAN IP — see the self-hosting guide.\n'
)
body = ''.join(out)
if dest == '/dev/stdout':
    sys.stdout.write(header + body)
else:
    open(dest, 'w').write(header + body)
PY
