// <auto-generated />
using System;
using EasyDocs.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyDocs.Api.Data.Migrations
{
    [DbContext(typeof(EasyDocsDbContext))]
    partial class EasyDocsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyDocs.Api.Domain.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("UserId");

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .HasColumnType("text");

                    b.Property<string>("DecisionComment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("VersionId");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetId")
                        .HasColumnType("text");

                    b.Property<string>("TargetType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Blob", b =>
                {
                    b.Property<string>("Sha256")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Sha256");

                    b.ToTable("Blobs");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MergedIntoVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RootVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MergedIntoVersionId");

                    b.HasIndex("RootVersionId");

                    b.HasIndex("DocumentId", "Ordinal")
                        .IsUnique();

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ForkedFromVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionCounterMajor")
                        .HasColumnType("integer");

                    b.Property<int>("VersionCounterMinor")
                        .HasColumnType("integer");

                    b.Property<int>("VersionCounterRev")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FolderId");

                    b.HasIndex("ForkedFromVersionId");

                    b.HasIndex("OrgId");

                    b.HasIndex("ParentDocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.DocumentMember", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentMembers");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BlobSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Major")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MergeParentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Minor")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfBlobSha256")
                        .HasColumnType("text");

                    b.Property<string>("PublishName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("PublishedKind")
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int>("SeqInBranch")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BlobSha256");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentId");

                    b.HasIndex("MergeParentVersionId");

                    b.HasIndex("ParentVersionId");

                    b.HasIndex("PdfBlobSha256");

                    b.HasIndex("BranchId", "SeqInBranch")
                        .IsUnique();

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.EditSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BaseVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastCommittedSha")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseVersionId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("EditSessions");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("OrgId", "ParentId", "Name")
                        .IsUnique();

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocRole")
                        .HasColumnType("text");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("OrgId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.OrgMember", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrgId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrgMembers");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.PushRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CopyDocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MaterializedVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PushedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetDocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CopyDocumentId");

                    b.HasIndex("MaterializedVersionId");

                    b.HasIndex("PushedBy");

                    b.HasIndex("SourceVersionId");

                    b.HasIndex("TargetDocumentId");

                    b.ToTable("PushRequests");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("VersionId");

                    b.ToTable("ShareLinks");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.VersionDiff", b =>
                {
                    b.Property<string>("FromSha256")
                        .HasColumnType("text");

                    b.Property<string>("ToSha256")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Deletions")
                        .HasColumnType("integer");

                    b.Property<int?>("FormatChanges")
                        .HasColumnType("integer");

                    b.Property<string>("HtmlBlobSha256")
                        .HasColumnType("text");

                    b.Property<int?>("Insertions")
                        .HasColumnType("integer");

                    b.Property<int?>("Moves")
                        .HasColumnType("integer");

                    b.Property<string>("RedlineBlobSha256")
                        .HasColumnType("text");

                    b.HasKey("FromSha256", "ToSha256");

                    b.HasIndex("ToSha256");

                    b.ToTable("VersionDiffs");
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.ApiToken", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.ApprovalRequest", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Branch", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("MergedIntoVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("RootVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Document", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.Folder", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("ForkedFromVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyDocs.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.DocumentMember", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.DocumentVersion", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.Blob", null)
                        .WithMany()
                        .HasForeignKey("BlobSha256")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("MergeParentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyDocs.Api.Domain.Blob", null)
                        .WithMany()
                        .HasForeignKey("PdfBlobSha256")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.EditSession", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("BaseVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyDocs.Api.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Folder", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.Invitation", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.OrgMember", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.PushRequest", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("CopyDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("MaterializedVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("PushedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("SourceVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("TargetDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.ShareLink", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyDocs.Api.Domain.VersionDiff", b =>
                {
                    b.HasOne("EasyDocs.Api.Domain.Blob", null)
                        .WithMany()
                        .HasForeignKey("FromSha256")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyDocs.Api.Domain.Blob", null)
                        .WithMany()
                        .HasForeignKey("ToSha256")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
